const Alerts = require("../Models/Alert.Schema")
const { createNotification } = require("./notification.service")
const Users = require("../Models/user.schema")

// Create an alert record and push an in-app notification to SuperAdmin + Admin users
const createAlert = async (alertData) => {
    try {
        const alert = await Alerts.create({ ...alertData, isAutoGenerated: true })

        // Notify all SuperAdmin and Admin users about the new alert
        const managers = await Users.find({ role: { $in: ["SuperAdmin", "Admin"] }, isActive: true }, { _id: 1 }).lean()
        for (const manager of managers) {
            await createNotification({
                user: manager._id,
                type: "AlertTriggered",
                title: alertData.title,
                message: alertData.message,
                link: `/alerts`,
                linkedModel: "Alerts",
                linkedId: alert._id,
            })
        }

        return alert
    } catch (err) {
        console.error("[alert.service] createAlert failed:", err.message)
        return null
    }
}

// Bulk create alerts from an array — used by cron jobs (renewal.job, infra.job)
const createAlertsBulk = async (alertsArray) => {
    const results = []
    for (const data of alertsArray) {
        const alert = await createAlert(data)
        if (alert) results.push(alert)
    }
    return results
}

module.exports = { createAlert, createAlertsBulk }
