const mongoose = require("mongoose")

const AlertSchema = mongoose.Schema(
  {
    type: {
      type: String,
      enum: ["Client", "Infra", "Marketing", "Internal"],
      required: true,
    },
    subType: {
      type: String,
      enum: [
        "SubscriptionRenewal",
        "PaymentOverdue",
        "DomainExpiry",
        "HostingExpiry",
        "SSLExpiry",
        "AdBudgetLow",
        "AdPaused",
        "Custom",
      ],
      required: true,
    },

    title: {
      type: String,
      required: true,
      trim: true,           // e.g. "Renewal due: Ramesh - Web App"
    },
    message: {
      type: String,
      required: true,
      trim: true,           // Full alert message / SMS draft
    },
    severity: {
      type: String,
      enum: ["Info", "Warning", "Urgent"],
      default: "Info",
    },

    dueDate: {
      type: Date,
      required: true,
    },

    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customers",     // present for Client alerts
    },
    subscription: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Subscriptions", // present for Client → SubscriptionRenewal
    },
    software: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Softwares",     // present for Infra alerts
    },

    status: {
      type: String,
      enum: ["Pending", "Sent", "Resolved", "Snoozed", "Dismissed"],
      default: "Pending",
    },
    resolvedAt: {
      type: Date,
    },
    resolvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Users",
    },
    smsSent: {
      type: Boolean,
      default: false,
    },
    smsSentAt: {
      type: Date,
    },
    smsResponse: {
      type: String,       
    },

    snoozedUntil: {
      type: Date,
    },

    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Users",
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Users",        
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,      
    },
  },
  { timestamps: true }
)
AlertSchema.index({ status: 1, dueDate: 1 })
AlertSchema.index({ type: 1, status: 1 })
AlertSchema.index({ customer: 1, status: 1 })

const Alerts = mongoose.model("Alerts", AlertSchema)
module.exports = Alerts